# Generated by Django 5.0.6 on 2024-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
